# Changes here will be overwritten by Copier; AVOID EDITING MANUALLY
_src_path: gh:ika100/sdlc-foundry/templates/gitops-app
app_name: todo
cluster_server: https://kubernetes.default.svc
description: GitOps repo for todo
docker_registry: ghcr.io/ika100
github_org: ika100
platform_marketplace_ref: main
project_name: todo
